item:
  name: "&8* &6Shield &8*"
  inventory_name: '§8» §6Schild §8«'
  material: "ENDER_EYE"
  lore:
    - " &7Click to get &6Shield &7menu&7."

  inventory_deactivate_item_name: '§c§lDEAKTIVIEREN'
  inventory_deactivate_item_skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWZkZTNiZmNlMmQ4Y2I3MjRkZTg1NTZlNWVjMjFiN2YxNWY1ODQ2ODRhYjc4NTIxNGFkZDE2NGJlNzYyNGIifX19'
  inventory_activate_item_name: '§a§lAKTIVIEREN'
  inventory_activate_item_skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTllNGJkY2YxNzJkNWRjNzdjMmJkNGUzN2FkOTg1Mzk5YTlmMmNkZWJmNzI0NjM5MjllYTRiNjY2ZWY2ZjgwIn19fQ=='
  sound:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP
    volume: 3
    pitch: 1
  on_join:
    enabled: true
    auto_activate: true
    slot: 0
  shield:
    knockback-rate: 2
    hight: 1
    distance: 5